/// Flutter icons Khadi
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Khadi
///      fonts:
///       - asset: fonts/Khadi.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'Khadi';
  static const String? _kFontPkg = null;

  static const IconData disclaimer = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accesories = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grocery = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beauty = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData men = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData women = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacypolicy = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myaddress = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shareapp = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData khadidrawer = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backword = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowrightbold = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
