// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcbblr4-2vdGgyZkzTiV1UqdmeUASUsrI',
    appId: '1:529537759885:web:d75bf43eb8ccbb43d3c0c4',
    messagingSenderId: '529537759885',
    projectId: 'e-commerce-app-fe3ed',
    authDomain: 'e-commerce-app-fe3ed.firebaseapp.com',
    storageBucket: 'e-commerce-app-fe3ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTXcKR17a-_XeM9XVYQBLMHlTLr_YQLA',
    appId: '1:529537759885:android:898c8f2e5bcc5ffdd3c0c4',
    messagingSenderId: '529537759885',
    projectId: 'e-commerce-app-fe3ed',
    storageBucket: 'e-commerce-app-fe3ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBej6cCNaM4vgjUItb9pL-ICN09w5xaoQs',
    appId: '1:529537759885:ios:c3fb7ef45522c7f6d3c0c4',
    messagingSenderId: '529537759885',
    projectId: 'e-commerce-app-fe3ed',
    storageBucket: 'e-commerce-app-fe3ed.appspot.com',
    iosBundleId: 'com.example.eCommerceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBej6cCNaM4vgjUItb9pL-ICN09w5xaoQs',
    appId: '1:529537759885:ios:c3fb7ef45522c7f6d3c0c4',
    messagingSenderId: '529537759885',
    projectId: 'e-commerce-app-fe3ed',
    storageBucket: 'e-commerce-app-fe3ed.appspot.com',
    iosBundleId: 'com.example.eCommerceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcbblr4-2vdGgyZkzTiV1UqdmeUASUsrI',
    appId: '1:529537759885:web:8fd88fac289ca71ed3c0c4',
    messagingSenderId: '529537759885',
    projectId: 'e-commerce-app-fe3ed',
    authDomain: 'e-commerce-app-fe3ed.firebaseapp.com',
    storageBucket: 'e-commerce-app-fe3ed.appspot.com',
  );
}
