import 'package:dartz/dartz.dart';
import 'package:e_commerce_application/data/address/models/address_model.dart';
import 'package:e_commerce_application/data/address/source/address_api_service.dart';
import 'package:e_commerce_application/domain/address/entity/address_entity.dart';
import 'package:e_commerce_application/domain/address/repository/address_repository.dart';
import 'package:e_commerce_application/service_locator.dart';

class AddressRepositoryImpl extends AddressRepository {
  final AddressApiService _addressApiService = sl<AddressApiService>();

  @override
  Future<Either<String, List<AddressEntity>>> getAddresses() async {
    final response = await _addressApiService.getAddresses();
    return response.fold(
      (error) => Left(error),
      (data) {
        try {
          final list = (data as List)
              .map((item) => AddressModel.fromJson(item as Map<String, dynamic>))
              .toList();
          return Right(list);
        } catch (e) {
          return Left(e.toString());
        }
      },
    );
  }

  @override
  Future<Either<String, AddressEntity>> addAddress(AddressEntity address) async {
    final model = address.toModel();
    final jsonMap = model.toJson();
    // remove id before sending since it's generated by DB
    jsonMap.remove('id');
    
    final response = await _addressApiService.addAddress(jsonMap);
    return response.fold(
      (error) => Left(error),
      (data) {
        try {
          final created = AddressModel.fromJson(data as Map<String, dynamic>);
          return Right(created);
        } catch (e) {
          return Left(e.toString());
        }
      },
    );
  }

  @override
  Future<Either<String, AddressEntity>> updateAddress(AddressEntity address) async {
    final model = address.toModel();
    final jsonMap = model.toJson();
    final response = await _addressApiService.updateAddress(address.id, jsonMap);
    return response.fold(
      (error) => Left(error),
      (data) {
        try {
          final updated = AddressModel.fromJson(data as Map<String, dynamic>);
          return Right(updated);
        } catch (e) {
          return Left(e.toString());
        }
      },
    );
  }

  @override
  Future<Either<String, String>> deleteAddress(String id) async {
    final response = await _addressApiService.deleteAddress(id);
    return response.fold(
      (error) => Left(error),
      (data) => const Right('Address deleted successfully'),
    );
  }
}
